lints.workspace = true

[package]
name = "gix-testtools"
description = "Shared code for gitoxide crates to facilitate testing"
version = "0.16.1"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["/src/**/*", "/LICENSE-*"]
rust-version = "1.76"

[[bin]]
name = "jtt"
path = "src/main.rs"

[lib]
doctest = false

[features]
default = []
## Use instead of plain `tar` files, compress these to produce `tar.xz` files instead.
## This is useful if archives are uploaded into `git-lfs`, which doesn't have built-in compression
## and metering counts towards uncompressed bytes transferred.
xz = ["dep:xz2"]

[dependencies]
gix-lock = { version = "17.1.0", path = "../../gix-lock" }
gix-discover = { version = "0.40.1", path = "../../gix-discover" }
gix-worktree = { version = "0.41.0", path = "../../gix-worktree" }
gix-fs = { version = "0.15.0", path = "../../gix-fs" }
gix-tempfile = { version = "17.1.0", path = "../../gix-tempfile", default-features = false, features = ["signals"] }

winnow = { version = "0.7.7", features = ["simd"] }
fastrand = "2.0.0"
bstr = { version = "1.12.0", default-features = false }
crc = "3.0.0"
once_cell = "1.21.3"
tempfile = "3.19.1"
fs_extra = "1.2.0"
parking_lot = { version = "0.12.0" }
is_ci = "1.1.1"
io-close = "0.3.7"
tar = { version = "0.4.38", default-features = false }
xz2 = { version = "0.1.6", optional = true }

document-features = { version = "0.2.1", optional = true }
[target.'cfg(any(target_arch = "wasm32", target_os = "wasi"))'.dependencies]
gix-tempfile = { path = "../../gix-tempfile", default-features = false }
tempfile = {version = "3.19.1", features = ["nightly"]}

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "wasi")))'.dependencies]
gix-tempfile = { path = "../../gix-tempfile", default-features = false, features = ["signals"] }
io-close = "0.3.7"
tempfile = "3.19.1"

[dev-dependencies]
serial_test = { version = "3.1.0", default-features = false }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
