name: ci

on:
  push:
    branches:
      - main
      - 'run-ci/**'
      - '**/run-ci/**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: '1'

jobs:

  wasm:
    name: WebAssembly

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        target: [ wasm32-unknown-unknown, wasm32-wasip1, wasm32-wasip2 ]
        target: [ wasm32-wasip2 ]

    env:
      TARGET: ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup update nightly
          rustup default nightly
          rustup target add "$TARGET"
      - uses: Swatinem/rust-cache@v2
      - name: 'WASI only: crates without feature toggle'
        if: endsWith(matrix.target, '-wasi')
        run: |
          set +x
          for name in gix-sec; do
            (cd -- "$name" && cargo build --target "$TARGET")
          done
      - name: crates without feature toggles
        run: |
          set +x
          for name in gix-actor gix-attributes gix-bitmap gix-chunk gix-command gix-commitgraph gix-config-value gix-date gix-glob gix-hash gix-hashtable gix-mailmap gix-object gix-packetline gix-path gix-pathspec gix-prompt gix-quote gix-refspec gix-revision gix-traverse gix-url gix-validate; do
            (cd -- "$name" && cargo build --target "$TARGET")
          done
      - name: features of gix-features
        run: |
          set +x
          for feature in progress parallel io-pipe crc32 zlib zlib-rust-backend cache-efficiency-debug; do
            (cd gix-features && cargo build --features "$feature" --target "$TARGET")
          done
      - name: crates with 'wasm' feature
        run: |
          set +x
          for name in gix-pack; do
            (cd -- "$name" && cargo build --features wasm --target "$TARGET")
          done
      - name: gix-pack with all features (including wasm)
        run: cd gix-pack && cargo build --all-features --target "$TARGET"