name: ci

on:
  push:
    branches:
      - main
      - 'run-ci/**'
      - '**/run-ci/**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: '1'

jobs:
  pure-rust-build:
    runs-on: ubuntu-latest

    container: debian:stable-slim

    steps:
      - name: Prerequisites
        run: |
          prerequisites=(
            ca-certificates
            curl
            gcc  # rustc calls gcc to invoke the linker.
            libc-dev  # rustc, in the toolchain we are using, dynamically links to the system libc.
            nodejs
          )
          apt-get update
          apt-get install --no-install-recommends -y -- "${prerequisites[@]}"
        shell: bash  # This step needs `bash`, and the default in container jobs is `sh`.
      - uses: actions/checkout@v4
        with:
          ref: ${{ gitea.ref }}
      - name: Verify that we are in an environment with limited dev tools
        run: |
          set -x
          for package in cmake g++ libssl-dev make pkgconf pkg-config; do
            if dpkg-query --status -- "$package"; then
              exit 1
            fi
          done
          for cmd in cmake g++ make pkgconf pkg-config; do
            if command -v -- "$cmd"; then
              exit 1
            fi
          done
      - name: Install Rust via Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
            sh -s -- -y --profile minimal
      - name: Add Rust tools to path
        run: echo "PATH=$HOME/.cargo/bin:$PATH" >> "$GITHUB_ENV"
      - name: Generate dependency tree
        run: cargo tree --locked --no-default-features --features max-pure > tree.txt
      - name: Scan for dependencies that build C or C++ code
        run: |
          pattern='.*\b(-sys|cc|cmake|pkg-config|vcpkg)\b.*'
          ! GREP_COLORS='ms=30;48;5;214' grep --color=always -Ex -C 1000000 -e "$pattern" tree.txt
        continue-on-error: true
      - name: Check for unrecognized *-sys dependencies
        run: |
          ! grep -qP '(?<!\blinux-raw)-sys\b' tree.txt
      - name: Wrap cc1 (and cc1plus if present) to record calls
        run: |
          set -o noclobber  # Catch any collisions with existing entries in /usr/local.

          # Define the wrapper script for a compiler driver (for cc1 or cc1plus). This wrapper
          # records calls, then delegates to the executable it wraps. When recording calls, writes
          # to the log are synchronized so fragments of separate log entries aren't interleaved,
          # even in concurrent runs. This wrapper knows what executable it is wrapping because,
          # when deployed, this wrapper (or a symlink) replaces that executable, which will itself
          # have been moved aside by being renamed with a `.orig` suffix, so this can call it.
          cat >/usr/local/bin/wrapper1 <<'EOF'
          #!/bin/sh
          set -e
          printf '%s\n' "$0 $*" |
            flock /run/lock/wrapper1.fbd136bd-9b1b-448d-84a9-e18be53ae63c.lock \
            tee -a -- /var/log/wrapper1.log ~/display >/dev/null  # We'll link ~/display later.
          exec "$0.orig" "$@"
          EOF

          # Define the script that performs the wrapping. This script shall be run once for each
          # executable to be wrapped, renaming it with a `.orig` suffix and replacing it with a
          # symlink to the wrapper script, defined above.
          cat >/usr/local/bin/wrap1 <<'EOF'
          #!/bin/sh
          set -e
          dir="$(dirname -- "$1")"
          base="$(basename -- "$1")"
          cd -- "$dir"
          mv -- "$base" "$base.orig"
          ln -s -- /usr/local/bin/wrapper1 "$base"
          EOF

          # Define a helper file that, when sourced, wires up the `~/display` symlink `wrapper1`
          # uses to report calls as GitHub Actions step output (in addition to writing them to a
          # log file). This is needed because stdout and stderr are both redirected elsewhere when
          # the wrapper actually runs, and `/dev/tty` is not usable. This must be sourced in the
          # same step as the `cargo` command that causes wrapped executables to be run, because
          # different steps write to different pipe objects. (This also needs the shell that
          # sourced it to remain running. But that is not the cause of the underlying limitation.)
          cat >/usr/local/bin/set-display.sh <<'EOF'
          ln -s -- "/proc/$$/fd/1" ~/display
          EOF

          chmod +x /usr/local/bin/wrapper1 /usr/local/bin/wrap1
          mkdir /run/lock/wrapper1.fbd136bd-9b1b-448d-84a9-e18be53ae63c.lock

          find /usr/lib/gcc \( -name cc1 -o -name cc1plus \) \
            -print -exec /usr/local/bin/wrap1 {} \;
      - name: Build max-pure with limited dev tools and log cc1
        run: |
          . /usr/local/bin/set-display.sh
          cargo install --debug --locked --no-default-features --features max-pure --path .
      - name: Show logged C and C++ compilations (should be none)
        run: |
          ! cat /var/log/wrapper1.log
        continue-on-error: true

  wasm:
    name: WebAssembly

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        target: [ wasm32-unknown-unknown, wasm32-wasip1, wasm32-wasip2 ]
        target: [ wasm32-wasip2 ]

    env:
      TARGET: ${{ matrix.target }}

    steps:
      - name: Prerequisites
        run: |
          prerequisites=(
            ca-certificates
            curl
            gcc  # rustc calls gcc to invoke the linker.
            libc-dev  # rustc, in the toolchain we are using, dynamically links to the system libc.
            nodejs
          )
          apt-get update
          apt-get install --no-install-recommends -y -- "${prerequisites[@]}"
#          apk update
#          apk add --no-cache nodejs
          # zstd make cmake gcc g++ bash git musl-dev tar
      - uses: actions/checkout@v4
        with:
          ref: ${{ gitea.ref }}
#      - name: Install Rust via Rustup
#        run: |
#          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
#            sh -s -- -y --profile minimal
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs
#          |
#            sh -s -- -y --profile minimal
          . "$HOME/.cargo/env"
          rustup update nightly
          rustup default nightly
          rustup target add "$TARGET"
      - uses: Swatinem/rust-cache@v2
      - name: 'WASI only: crates without feature toggle'
        if: endsWith(matrix.target, '-wasi')
        run: |
          set +x
          for name in gix-sec; do
            (cd -- "$name" && cargo build --target "$TARGET")
          done
      - name: crates without feature toggles
        run: |
          set +x
          for name in gix-actor gix-attributes gix-bitmap gix-chunk gix-command gix-commitgraph gix-config-value gix-date gix-glob gix-hash gix-hashtable gix-mailmap gix-object gix-packetline gix-path gix-pathspec gix-prompt gix-quote gix-refspec gix-revision gix-traverse gix-url gix-validate; do
            (cd -- "$name" && cargo build --target "$TARGET")
          done
      - name: features of gix-features
        run: |
          set +x
          for feature in progress parallel io-pipe crc32 zlib zlib-rust-backend cache-efficiency-debug; do
            (cd gix-features && cargo build --features "$feature" --target "$TARGET")
          done
      - name: crates with 'wasm' feature
        run: |
          set +x
          for name in gix-pack; do
            (cd -- "$name" && cargo build --features wasm --target "$TARGET")
          done
      - name: gix-pack with all features (including wasm)
        run: cd gix-pack && cargo build --all-features --target "$TARGET"